// constants

export const ADD_USER = "ADD_USER";
export const ADD_USER_RESPONSE_SUCCESS = "ADD_USER_RESPONSE_SUCCESS";
export const ADD_USER_RESPONSE_ERROR = "ADD_USER_RESPONSE_ERROR";

export const GET_CHARACTERS = "GET_CHARACTERS";
export const GET_CHARACTERS_SUCCESS = "GET_CHARACTERS_SUCCESS";
export const GET_CHARACTERS_ERROR = "GET_CHARACTERS_ERROR";

export const VALIDATE_USER = "VALIDATE_USER";
export const VALIDATE_USER_SUCCESS = "VERROR =_USER_SUCCESS";
export const VALIDATE_USER_ERROR = "VALIDATE_USER_ERROR";
